theme = "dracula"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
interval = 10
chip = "*-isa-*"

[[block]]
block = "sound"

[[block]]
block = "dnf"
interval = 3600
critical_updates_regex = "(linux|linux-lts|linux-zen)"
on_click = "dnf list -q --upgrades | tail -n +2 | rofi -dmenu"

[[block]]
block = "xrandr"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"


